# Generated by Django 2.2.1 on 2019-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('model_year', models.CharField(choices=[('2018', '2019')], max_length=4)),
                ('screen_size', models.CharField(choices=[('32', '32'), ('40', '40'), ('43', '43'), ('55', '55')], max_length=2)),
                ('resolution', models.CharField(choices=[('FHD', 'FHD'), ('UHD', 'UHD')], max_length=3)),
                ('hdr', models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('system_os', models.CharField(choices=[('Tizen', 'Tizen'), ('Orsay', 'Orsay')], max_length=8)),
                ('content', models.TextField(default='Describe key features', max_length=255)),
            ],
        ),
    ]
