# Generated by Django 2.2.1 on 2019-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvmodel',
            name='model_year',
            field=models.CharField(choices=[('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2019', '2019')], max_length=4),
        ),
    ]
