# Generated by Django 2.2.1 on 2019-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_models', '0002_auto_20190614_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvmodel',
            name='manual',
            field=models.URLField(default='url', verbose_name='here lies url'),
        ),
    ]
