# Generated by Django 2.2.1 on 2019-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_models', '0003_tvmodel_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvmodel',
            name='manual',
            field=models.URLField(blank=True, verbose_name='here lies url'),
        ),
        migrations.AlterField(
            model_name='tvmodel',
            name='screen_size',
            field=models.CharField(choices=[('32', '32'), ('40', '40'), ('43', '43'), ('49', '49'), ('55', '55')], max_length=2),
        ),
    ]
